### ISSUE TITLE
ImportError: cannot import name 'train' from 'samples.pytorch.trainer'

### ISSUE THREAD

**Issue by indritnallbani** [snu-adsl/DEEP-BO#5]
When i try to run hpo_runner with cifar100  there is an error that comes up. As far as I understood, it is trying to call a method from a class found at file: samples/pytorch/trainer.py
Function causing the error:   " from .pytorch.trainer import train" 

@objective_function
def tune_efficientnet_cifar100(config, fail_err=0.99, **kwargs):
    from .pytorch.trainer import train

    global START_TIME
    START_TIME = time.time()
    run_id = get_resource().get_id()

    max_epoch = 90
    if "max_iters" in kwargs:
        if "iter_unit" in kwargs and kwargs["iter_unit"] == "epoch":
            max_epoch = kwargs["max_iters"]   

    if 'job_id' in kwargs:
        job_id = kwargs['job_id']
    else:
        job_id = get_resource().get_id() 
    cfg_path = create_yaml_config(run_id, 'cifar100', config, max_epoch)
    print(cfg_path)

    train(cfg_path, epoch_cb=update_epoch_acc)

Error that occurs:

Traceback (most recent call last):
  File "/home/indrit/anaconda3/envs/deepboo/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/indrit/anaconda3/envs/deepboo/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/indrit/DEEP-BO/samples/targets.py", line 153, in tune_efficientnet_cifar100
    from .pytorch.trainer import train
ImportError: cannot import name 'train' from 'samples.pytorch.trainer' (/home/indrit/DEEP-BO/samples/pytorch/trainer.py)

**Comment by hyunghunny** [comment]
First of all, thank you for your interest. 

I found this is a bug caused by my careless refactoring.
While I fixed this issue, I also fixed some of the other issues due to the Pytorch update. 

Please try using the latest version of DEEP-BO by using `git pull`
You can also find the change [here](https://github.com/SNU-DRL/DEEP-BO/commit/495353c9857c3f5d8eaff6ae03d62c4f0949a237)
Note that you need to install **gpustat** tool by `pip install gpustat` when you try using NVidia GPU. 

Although I hope you can properly run this sample code; if this issue is not resolved, let me know here. 

Again, I appreciate your contribution.
Thank you.

**Comment by indritnallbani** [comment]
issues fixed with last update
